# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pisces',
                'doc_host': 'https://Arcascope.github.io',
                'git_url': 'https://github.com/Arcascope/pisces',
                'lib_path': 'pisces'},
  'syms': {'pisces.core': {'pisces.core.foo': ('core.html#foo', 'pisces/core.py')}}}
